In [3]:
import numpy as np
import pandas as pd

In [4]:
df = pd.read_csv('/content/diabetes.csv')

In [5]:
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [6]:
df.corr()['Outcome']

Pregnancies                 0.221898
Glucose                     0.466581
BloodPressure               0.065068
SkinThickness               0.074752
Insulin                     0.130548
BMI                         0.292695
DiabetesPedigreeFunction    0.173844
Age                         0.238356
Outcome                     1.000000
Name: Outcome, dtype: float64

In [7]:
X = df.iloc[:, :-1].values
y = df.iloc[:, -1].values

In [8]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X = scaler.fit_transform(X)

In [9]:
X

array([[ 0.63994726,  0.84832379,  0.14964075, ...,  0.20401277,
         0.46849198,  1.4259954 ],
       [-0.84488505, -1.12339636, -0.16054575, ..., -0.68442195,
        -0.36506078, -0.19067191],
       [ 1.23388019,  1.94372388, -0.26394125, ..., -1.10325546,
         0.60439732, -0.10558415],
       ...,
       [ 0.3429808 ,  0.00330087,  0.14964075, ..., -0.73518964,
        -0.68519336, -0.27575966],
       [-0.84488505,  0.1597866 , -0.47073225, ..., -0.24020459,
        -0.37110101,  1.17073215],
       [-0.84488505, -0.8730192 ,  0.04624525, ..., -0.20212881,
        -0.47378505, -0.87137393]])

In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)

In [85]:
import tensorflow as tf
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense, Dropout

In [12]:
X.shape

(768, 8)

In [13]:
model = Sequential()
model.add(Dense(32, activation='relu', input_dim=8))
model.add(Dense(1, activation='sigmoid'))

/usr/local/lib/python3.13/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [14]:
model.compile(optimizer='Adam', loss='binary_crossentropy', metrics=['accuracy'])

In [15]:
model.fit(X_train, y_train, batch_size=32, epochs=100, validation_data=(X_test, y_test))

Epoch 1/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - accuracy: 0.4153 - loss: 0.7792 - val_accuracy: 0.4545 - val_loss: 0.7594
Epoch 2/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.5570 - loss: 0.7007 - val_accuracy: 0.6169 - val_loss: 0.6872
Epoch 3/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6564 - loss: 0.6430 - val_accuracy: 0.6688 - val_loss: 0.6386
Epoch 4/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6971 - loss: 0.6015 - val_accuracy: 0.6883 - val_loss: 0.5998
Epoch 5/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7215 - loss: 0.5710 - val_accuracy: 0.7078 - val_loss: 0.5684
Epoch 6/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7248 - loss: 0.5465 - val_accuracy: 0.7403 - val_loss: 0.5460
Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7345 - loss: 0.5278 - val_accuracy: 0.7662 - val_loss: 0.5278
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7492 - loss: 0.5122 - val_accuracy: 0.7922 - val_loss: 0.5117
Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7638 - loss: 0.5012 - val_accuracy: 0.7987 - val_loss: 0.5007
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7704 - loss: 0.4922 - val_accuracy: 0.7792 - val_loss: 0.4933
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7785 - loss: 0.4849 - val_accuracy: 0.7727 - val_loss: 0.4869
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7785 - loss: 0.4787 - val_accuracy: 0.7792 - val_loss: 0.4834
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7785 - loss: 0.4755 - val_accuracy: 0.7792 - val_loss: 0.4814
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7850 - loss: 0.4707 - val_accuracy: 0.7792 - val_loss: 0.4772
Epoch 15/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7850 - loss: 0.4670 - val_accuracy: 0.7727 - val_loss: 0.4747
Epoch 16/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7899 - loss: 0.4637 - val_accuracy: 0.7792 - val_loss: 0.4717
Epoch 17/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4612 - val_accuracy: 0.7792 - val_loss: 0.4699
Epoch 18/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7883 - loss: 0.4588 - val_accuracy: 0.7792 - val_loss: 0.4680
Epoch 19/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7883 - loss: 0.4572 - val_accuracy: 0.7857 - val_loss: 0.4656
Epoch 20/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7834 - loss: 0.4551 - val_accuracy: 0.7857 - val_loss: 0.4645
Epoch 21/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7883 - loss: 0.4541 - val_accuracy: 0.7792 - val_loss: 0.4648
Epoch 22/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7850 - loss: 0.4523 - val_accuracy: 0.7792 - val_loss: 0.4633
Epoch 23/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7866 - loss: 0.4515 - val_accuracy: 0.7727 - val_loss: 0.4631
Epoch 24/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7834 - loss: 0.4501 - val_accuracy: 0.7727 - val_loss: 0.4630
Epoch 25/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7866 - loss: 0.4492 - val_accuracy: 0.7857 - val_loss: 0.4616
Epoch 26/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7883 - loss: 0.4485 - val_accuracy: 0.7857 - val_loss: 0.4609
Epoch 27/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7866 - loss: 0.4478 - val_accuracy: 0.7857 - val_loss: 0.4596
Epoch 28/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7866 - loss: 0.4471 - val_accuracy: 0.7792 - val_loss: 0.4603
Epoch 29/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7850 - loss: 0.4464 - val_accuracy: 0.7792 - val_loss: 0.4601
Epoch 30/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7834 - loss: 0.4454 - val_accuracy: 0.7727 - val_loss: 0.4615
Epoch 31/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7866 - loss: 0.4446 - val_accuracy: 0.7922 - val_loss: 0.4597
Epoch 32/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7850 - loss: 0.4441 - val_accuracy: 0.7727 - val_loss: 0.4602
Epoch 33/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7818 - loss: 0.4440 - val_accuracy: 0.7727 - val_loss: 0.4607
Epoch 34/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7834 - loss: 0.4427 - val_accuracy: 0.7857 - val_loss: 0.4587
Epoch 35/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7932 - loss: 0.4427 - val_accuracy: 0.7857 - val_loss: 0.4581
Epoch 36/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4423 - val_accuracy: 0.7792 - val_loss: 0.4584
Epoch 37/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4414 - val_accuracy: 0.7792 - val_loss: 0.4584
Epoch 38/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7899 - loss: 0.4410 - val_accuracy: 0.7857 - val_loss: 0.4568
Epoch 39/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4402 - val_accuracy: 0.7792 - val_loss: 0.4568
Epoch 40/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4405 - val_accuracy: 0.7922 - val_loss: 0.4567
Epoch 41/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7866 - loss: 0.4395 - val_accuracy: 0.7922 - val_loss: 0.4572
Epoch 42/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4391 - val_accuracy: 0.7792 - val_loss: 0.4593
Epoch 43/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7899 - loss: 0.4388 - val_accuracy: 0.7922 - val_loss: 0.4591
Epoch 44/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7883 - loss: 0.4383 - val_accuracy: 0.7792 - val_loss: 0.4588
Epoch 45/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7883 - loss: 0.4373 - val_accuracy: 0.7987 - val_loss: 0.4576
Epoch 46/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7883 - loss: 0.4369 - val_accuracy: 0.7987 - val_loss: 0.4565
Epoch 47/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7850 - loss: 0.4368 - val_accuracy: 0.7987 - val_loss: 0.4556
Epoch 48/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7883 - loss: 0.4357 - val_accuracy: 0.7922 - val_loss: 0.4560
Epoch 49/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7883 - loss: 0.4356 - val_accuracy: 0.7922 - val_loss: 0.4559
Epoch 50/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7866 - loss: 0.4356 - val_accuracy: 0.7922 - val_loss: 0.4563
Epoch 51/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7899 - loss: 0.4348 - val_accuracy: 0.7922 - val_loss: 0.4559
Epoch 52/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7948 - loss: 0.4345 - val_accuracy: 0.7857 - val_loss: 0.4553
Epoch 53/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7899 - loss: 0.4344 - val_accuracy: 0.7922 - val_loss: 0.4559
Epoch 54/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7899 - loss: 0.4335 - val_accuracy: 0.7857 - val_loss: 0.4549
Epoch 55/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7899 - loss: 0.4331 - val_accuracy: 0.7922 - val_loss: 0.4543
Epoch 56/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4331 - val_accuracy: 0.7987 - val_loss: 0.4538
Epoch 57/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7899 - loss: 0.4325 - val_accuracy: 0.7922 - val_loss: 0.4545
Epoch 58/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7932 - loss: 0.4320 - val_accuracy: 0.7922 - val_loss: 0.4536
Epoch 59/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4312 - val_accuracy: 0.7922 - val_loss: 0.4536
Epoch 60/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7948 - loss: 0.4310 - val_accuracy: 0.7857 - val_loss: 0.4534
Epoch 61/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7932 - loss: 0.4313 - val_accuracy: 0.7987 - val_loss: 0.4537
Epoch 62/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4304 - val_accuracy: 0.7857 - val_loss: 0.4541
Epoch 63/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7948 - loss: 0.4302 - val_accuracy: 0.7857 - val_loss: 0.4539
Epoch 64/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7948 - loss: 0.4299 - val_accuracy: 0.7857 - val_loss: 0.4534
Epoch 65/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7899 - loss: 0.4295 - val_accuracy: 0.7922 - val_loss: 0.4516
Epoch 66/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7932 - loss: 0.4294 - val_accuracy: 0.7922 - val_loss: 0.4522
Epoch 67/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7948 - loss: 0.4289 - val_accuracy: 0.7987 - val_loss: 0.4513
Epoch 68/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7964 - loss: 0.4287 - val_accuracy: 0.7922 - val_loss: 0.4543
Epoch 69/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7980 - loss: 0.4287 - val_accuracy: 0.8052 - val_loss: 0.4528
Epoch 70/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7932 - loss: 0.4283 - val_accuracy: 0.7987 - val_loss: 0.4525
Epoch 71/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7932 - loss: 0.4274 - val_accuracy: 0.7857 - val_loss: 0.4538
Epoch 72/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7948 - loss: 0.4275 - val_accuracy: 0.7987 - val_loss: 0.4519
Epoch 73/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7915 - loss: 0.4274 - val_accuracy: 0.7987 - val_loss: 0.4509
Epoch 74/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7915 - loss: 0.4267 - val_accuracy: 0.7987 - val_loss: 0.4502
Epoch 75/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7899 - loss: 0.4263 - val_accuracy: 0.7987 - val_loss: 0.4490
Epoch 76/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7883 - loss: 0.4266 - val_accuracy: 0.7987 - val_loss: 0.4490
Epoch 77/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7932 - loss: 0.4257 - val_accuracy: 0.8052 - val_loss: 0.4486
Epoch 78/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7932 - loss: 0.4256 - val_accuracy: 0.8052 - val_loss: 0.4495
Epoch 79/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7932 - loss: 0.4249 - val_accuracy: 0.8052 - val_loss: 0.4484
Epoch 80/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7883 - loss: 0.4245 - val_accuracy: 0.8117 - val_loss: 0.4493
Epoch 81/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7883 - loss: 0.4241 - val_accuracy: 0.8052 - val_loss: 0.4502
Epoch 82/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4241 - val_accuracy: 0.7922 - val_loss: 0.4501
Epoch 83/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7964 - loss: 0.4242 - val_accuracy: 0.8052 - val_loss: 0.4489
Epoch 84/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7948 - loss: 0.4231 - val_accuracy: 0.8117 - val_loss: 0.4482
Epoch 85/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7932 - loss: 0.4229 - val_accuracy: 0.8052 - val_loss: 0.4492
Epoch 86/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7997 - loss: 0.4225 - val_accuracy: 0.8052 - val_loss: 0.4495
Epoch 87/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7997 - loss: 0.4223 - val_accuracy: 0.8117 - val_loss: 0.4492
Epoch 88/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7948 - loss: 0.4218 - val_accuracy: 0.8117 - val_loss: 0.4486
Epoch 89/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7964 - loss: 0.4218 - val_accuracy: 0.8052 - val_loss: 0.4503
Epoch 90/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7980 - loss: 0.4216 - val_accuracy: 0.7987 - val_loss: 0.4496
Epoch 91/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7997 - loss: 0.4209 - val_accuracy: 0.7987 - val_loss: 0.4489
Epoch 92/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7997 - loss: 0.4207 - val_accuracy: 0.8052 - val_loss: 0.4488
Epoch 93/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8013 - loss: 0.4204 - val_accuracy: 0.8052 - val_loss: 0.4484
Epoch 94/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7980 - loss: 0.4196 - val_accuracy: 0.8117 - val_loss: 0.4465
Epoch 95/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7948 - loss: 0.4197 - val_accuracy: 0.8052 - val_loss: 0.4476
Epoch 96/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7964 - loss: 0.4189 - val_accuracy: 0.8117 - val_loss: 0.4468
Epoch 97/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7997 - loss: 0.4185 - val_accuracy: 0.7987 - val_loss: 0.4472
Epoch 98/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7980 - loss: 0.4183 - val_accuracy: 0.8052 - val_loss: 0.4465
Epoch 99/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8029 - loss: 0.4182 - val_accuracy: 0.7987 - val_loss: 0.4457
Epoch 100/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7980 - loss: 0.4180 - val_accuracy: 0.8052 - val_loss: 0.4469

In [16]:
# 1. select appropiate optimizer
# 2. num of node in a lyers
# 3. num of hidden layers
# 4. All in all one model

In [17]:
!pip install -q keras-tuner

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 129.4/129.4 kB 3.8 MB/s eta 0:00:00

In [18]:
import keras_tuner as kt

In [19]:
def build_model(hp):
  model = keras.Sequential()
  model.add(Dense(32, activation='relu', input_dim=8))
  model.add(keras.layers.Dense(1, activation='sigmoid'))
  model.compile(
      optimizer=hp.Choice('optimizer', ['sgd', 'rmsprop', 'adam', 'adadelta']),
                loss='binary_crossentropy',
                metrics=['accuracy']
  )
  return model

In [20]:
tuner = kt.RandomSearch(
    build_model,
    objective='val_accuracy',
    max_trials=5,
    directory='my_tuning',
    project_name='optimizer_test',
    overwrite=True
)

In [21]:
tuner.search(X_train, y_train, epochs=5, validation_data=(X_test, y_test))

Trial 4 Complete [00h 00m 02s]
val_accuracy: 0.8116883039474487

Best val_accuracy So Far: 0.8116883039474487
Total elapsed time: 00h 00m 20s

In [22]:

tuner.get_best_hyperparameters()[0].values

{'optimizer': 'rmsprop'}

In [23]:
model = tuner.get_best_models(num_models=1)[0]

/usr/local/lib/python3.13/dist-packages/keras/src/saving/saving_lib.py:797: UserWarning: Skipping variable loading for optimizer 'rmsprop', because it has 2 variables whereas the saved optimizer has 6 variables.
  saveable.load_own_variables(weights_store.get(inner_path))

In [24]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 32)             │           288 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 321 (1.25 KB)

 Trainable params: 321 (1.25 KB)

 Non-trainable params: 0 (0.00 B)

In [25]:
model.fit(X_train, y_train, epochs=100, initial_epoch=6, validation_data=(X_test, y_test))

Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - accuracy: 0.7362 - loss: 0.5681 - val_accuracy: 0.7792 - val_loss: 0.5428
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7508 - loss: 0.5384 - val_accuracy: 0.7857 - val_loss: 0.5239
Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7606 - loss: 0.5209 - val_accuracy: 0.7792 - val_loss: 0.5089
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7704 - loss: 0.5081 - val_accuracy: 0.7922 - val_loss: 0.4978
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7638 - loss: 0.4977 - val_accuracy: 0.7857 - val_loss: 0.4890
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.7671 - loss: 0.4891 - val_accuracy: 0.7922 - val_loss: 0.4840
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.7687 - loss: 0.4822 - val_accuracy: 0.7922 - val_loss: 0.4790
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - accuracy: 0.7655 - loss: 0.4776 - val_accuracy: 0.7987 - val_loss: 0.4766
Epoch 15/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7720 - loss: 0.4739 - val_accuracy: 0.7987 - val_loss: 0.4733
Epoch 16/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.7704 - loss: 0.4702 - val_accuracy: 0.8052 - val_loss: 0.4708
Epoch 17/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.7704 - loss: 0.4675 - val_accuracy: 0.8052 - val_loss: 0.4698
Epoch 18/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7704 - loss: 0.4653 - val_accuracy: 0.8052 - val_loss: 0.4689
Epoch 19/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - accuracy: 0.7720 - loss: 0.4629 - val_accuracy: 0.7987 - val_loss: 0.4691
Epoch 20/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - accuracy: 0.7752 - loss: 0.4614 - val_accuracy: 0.7987 - val_loss: 0.4684
Epoch 21/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 32ms/step - accuracy: 0.7769 - loss: 0.4593 - val_accuracy: 0.7922 - val_loss: 0.4687
Epoch 22/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - accuracy: 0.7736 - loss: 0.4582 - val_accuracy: 0.7987 - val_loss: 0.4679
Epoch 23/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 27ms/step - accuracy: 0.7752 - loss: 0.4572 - val_accuracy: 0.7987 - val_loss: 0.4676
Epoch 24/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - accuracy: 0.7736 - loss: 0.4560 - val_accuracy: 0.7987 - val_loss: 0.4679
Epoch 25/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.7785 - loss: 0.4548 - val_accuracy: 0.7922 - val_loss: 0.4681
Epoch 26/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - accuracy: 0.7736 - loss: 0.4538 - val_accuracy: 0.7922 - val_loss: 0.4680
Epoch 27/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.7720 - loss: 0.4528 - val_accuracy: 0.7922 - val_loss: 0.4672
Epoch 28/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - accuracy: 0.7752 - loss: 0.4521 - val_accuracy: 0.7922 - val_loss: 0.4665
Epoch 29/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - accuracy: 0.7736 - loss: 0.4511 - val_accuracy: 0.7922 - val_loss: 0.4668
Epoch 30/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.7720 - loss: 0.4507 - val_accuracy: 0.7922 - val_loss: 0.4665
Epoch 31/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - accuracy: 0.7720 - loss: 0.4497 - val_accuracy: 0.7922 - val_loss: 0.4672
Epoch 32/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.7720 - loss: 0.4488 - val_accuracy: 0.7922 - val_loss: 0.4681
Epoch 33/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - accuracy: 0.7769 - loss: 0.4484 - val_accuracy: 0.7922 - val_loss: 0.4685
Epoch 34/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7736 - loss: 0.4473 - val_accuracy: 0.7922 - val_loss: 0.4684
Epoch 35/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - accuracy: 0.7752 - loss: 0.4468 - val_accuracy: 0.7922 - val_loss: 0.4692
Epoch 36/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.7736 - loss: 0.4466 - val_accuracy: 0.7922 - val_loss: 0.4683
Epoch 37/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7752 - loss: 0.4459 - val_accuracy: 0.7922 - val_loss: 0.4682
Epoch 38/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7736 - loss: 0.4449 - val_accuracy: 0.7922 - val_loss: 0.4683
Epoch 39/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7752 - loss: 0.4449 - val_accuracy: 0.7922 - val_loss: 0.4687
Epoch 40/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7720 - loss: 0.4444 - val_accuracy: 0.7922 - val_loss: 0.4683
Epoch 41/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7752 - loss: 0.4436 - val_accuracy: 0.7922 - val_loss: 0.4684
Epoch 42/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7752 - loss: 0.4434 - val_accuracy: 0.7922 - val_loss: 0.4686
Epoch 43/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7736 - loss: 0.4424 - val_accuracy: 0.7922 - val_loss: 0.4683
Epoch 44/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7752 - loss: 0.4418 - val_accuracy: 0.7922 - val_loss: 0.4676
Epoch 45/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7785 - loss: 0.4413 - val_accuracy: 0.7922 - val_loss: 0.4677
Epoch 46/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7769 - loss: 0.4410 - val_accuracy: 0.7922 - val_loss: 0.4674
Epoch 47/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7736 - loss: 0.4405 - val_accuracy: 0.7922 - val_loss: 0.4678
Epoch 48/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7801 - loss: 0.4400 - val_accuracy: 0.7922 - val_loss: 0.4676
Epoch 49/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7752 - loss: 0.4397 - val_accuracy: 0.7922 - val_loss: 0.4675
Epoch 50/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7752 - loss: 0.4389 - val_accuracy: 0.7922 - val_loss: 0.4679
Epoch 51/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7801 - loss: 0.4385 - val_accuracy: 0.7922 - val_loss: 0.4682
Epoch 52/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7834 - loss: 0.4384 - val_accuracy: 0.7922 - val_loss: 0.4681
Epoch 53/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7801 - loss: 0.4376 - val_accuracy: 0.7987 - val_loss: 0.4679
Epoch 54/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7834 - loss: 0.4371 - val_accuracy: 0.7987 - val_loss: 0.4693
Epoch 55/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7752 - loss: 0.4367 - val_accuracy: 0.7922 - val_loss: 0.4687
Epoch 56/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7801 - loss: 0.4358 - val_accuracy: 0.8052 - val_loss: 0.4697
Epoch 57/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7818 - loss: 0.4356 - val_accuracy: 0.7987 - val_loss: 0.4694
Epoch 58/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7850 - loss: 0.4350 - val_accuracy: 0.7922 - val_loss: 0.4699
Epoch 59/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7883 - loss: 0.4350 - val_accuracy: 0.7857 - val_loss: 0.4700
Epoch 60/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7850 - loss: 0.4344 - val_accuracy: 0.7922 - val_loss: 0.4695
Epoch 61/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7866 - loss: 0.4340 - val_accuracy: 0.7987 - val_loss: 0.4688
Epoch 62/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7850 - loss: 0.4337 - val_accuracy: 0.7922 - val_loss: 0.4692
Epoch 63/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7866 - loss: 0.4329 - val_accuracy: 0.7987 - val_loss: 0.4681
Epoch 64/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7850 - loss: 0.4330 - val_accuracy: 0.7922 - val_loss: 0.4690
Epoch 65/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7899 - loss: 0.4326 - val_accuracy: 0.7987 - val_loss: 0.4685
Epoch 66/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7883 - loss: 0.4321 - val_accuracy: 0.7987 - val_loss: 0.4679
Epoch 67/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7899 - loss: 0.4317 - val_accuracy: 0.7987 - val_loss: 0.4674
Epoch 68/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7899 - loss: 0.4314 - val_accuracy: 0.7987 - val_loss: 0.4681
Epoch 69/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7883 - loss: 0.4311 - val_accuracy: 0.7987 - val_loss: 0.4679
Epoch 70/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7915 - loss: 0.4307 - val_accuracy: 0.7987 - val_loss: 0.4691
Epoch 71/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7948 - loss: 0.4302 - val_accuracy: 0.7987 - val_loss: 0.4687
Epoch 72/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4298 - val_accuracy: 0.7987 - val_loss: 0.4690
Epoch 73/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7866 - loss: 0.4293 - val_accuracy: 0.7922 - val_loss: 0.4696
Epoch 74/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7948 - loss: 0.4287 - val_accuracy: 0.7857 - val_loss: 0.4691
Epoch 75/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4289 - val_accuracy: 0.7857 - val_loss: 0.4690
Epoch 76/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7899 - loss: 0.4283 - val_accuracy: 0.7922 - val_loss: 0.4689
Epoch 77/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7899 - loss: 0.4280 - val_accuracy: 0.7857 - val_loss: 0.4686
Epoch 78/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4275 - val_accuracy: 0.7987 - val_loss: 0.4690
Epoch 79/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4270 - val_accuracy: 0.7987 - val_loss: 0.4691
Epoch 80/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7948 - loss: 0.4267 - val_accuracy: 0.7857 - val_loss: 0.4691
Epoch 81/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7964 - loss: 0.4265 - val_accuracy: 0.7922 - val_loss: 0.4683
Epoch 82/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7932 - loss: 0.4261 - val_accuracy: 0.7857 - val_loss: 0.4681
Epoch 83/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7948 - loss: 0.4260 - val_accuracy: 0.7857 - val_loss: 0.4690
Epoch 84/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7948 - loss: 0.4251 - val_accuracy: 0.7922 - val_loss: 0.4686
Epoch 85/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7964 - loss: 0.4250 - val_accuracy: 0.7922 - val_loss: 0.4694
Epoch 86/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7932 - loss: 0.4247 - val_accuracy: 0.7987 - val_loss: 0.4691
Epoch 87/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7948 - loss: 0.4243 - val_accuracy: 0.7987 - val_loss: 0.4697
Epoch 88/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7980 - loss: 0.4241 - val_accuracy: 0.7857 - val_loss: 0.4701
Epoch 89/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7948 - loss: 0.4237 - val_accuracy: 0.7922 - val_loss: 0.4695
Epoch 90/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7964 - loss: 0.4232 - val_accuracy: 0.7922 - val_loss: 0.4696
Epoch 91/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7964 - loss: 0.4231 - val_accuracy: 0.7922 - val_loss: 0.4689
Epoch 92/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7980 - loss: 0.4229 - val_accuracy: 0.7922 - val_loss: 0.4697
Epoch 93/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7948 - loss: 0.4223 - val_accuracy: 0.7922 - val_loss: 0.4694
Epoch 94/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8013 - loss: 0.4218 - val_accuracy: 0.7922 - val_loss: 0.4696
Epoch 95/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8013 - loss: 0.4214 - val_accuracy: 0.7922 - val_loss: 0.4700
Epoch 96/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7964 - loss: 0.4218 - val_accuracy: 0.7922 - val_loss: 0.4692
Epoch 97/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7980 - loss: 0.4208 - val_accuracy: 0.7922 - val_loss: 0.4690
Epoch 98/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7964 - loss: 0.4206 - val_accuracy: 0.7922 - val_loss: 0.4690
Epoch 99/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8013 - loss: 0.4204 - val_accuracy: 0.7987 - val_loss: 0.4685
Epoch 100/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7964 - loss: 0.4201 - val_accuracy: 0.7987 - val_loss: 0.4695

In [26]:
def build_model(hp):
  model = keras.Sequential()

  units = hp.Int(8, 128, 38, 58)
  model.add(
      Dense(units=units,
      activation='relu',
            input_dim=8)
      )
  model.add(keras.layers.Dense(1, activation='sigmoid'))
  model.compile(optimizer='Adam', loss='binary_crossentropy', metrics=['accuracy'])
  return model

In [27]:
def build_model(hp):
  model = keras.Sequential()
  units = hp.Int('units', min_value=8, max_value=128, step=8)
  model.add(
      Dense(units=units,
            activation='relu',
            input_dim=8)
  )
  model.add(keras.layers.Dense(1, activation='sigmoid'))
  model.compile(optimizer='Adam', loss='binary_crossentropy', metrics=['accuracy'])
  return model

tuner = kt.RandomSearch(
    build_model,
    objective='val_accuracy',
    max_trials=5,
    directory='mydir',
    overwrite=True)

In [28]:
tuner.search(X_train, y_train, epochs=5, validation_data=(X_test, y_test))

Trial 5 Complete [00h 00m 03s]
val_accuracy: 0.7727272510528564

Best val_accuracy So Far: 0.8051947951316833
Total elapsed time: 00h 00m 13s

In [29]:
tuner.get_best_hyperparameters()[0].values

{'units': 104}

In [30]:
model = tuner.get_best_models(num_models=1)[0]

/usr/local/lib/python3.13/dist-packages/keras/src/saving/saving_lib.py:797: UserWarning: Skipping variable loading for optimizer 'adam', because it has 2 variables whereas the saved optimizer has 10 variables.
  saveable.load_own_variables(weights_store.get(inner_path))

In [31]:
model.fit(X_train, y_train, epochs=100, initial_epoch=6, validation_data=(X_test, y_test))

Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - accuracy: 0.7834 - loss: 0.4736 - val_accuracy: 0.7987 - val_loss: 0.4751
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7752 - loss: 0.4633 - val_accuracy: 0.7922 - val_loss: 0.4700
Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7818 - loss: 0.4581 - val_accuracy: 0.7987 - val_loss: 0.4697
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7818 - loss: 0.4536 - val_accuracy: 0.7922 - val_loss: 0.4704
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7883 - loss: 0.4521 - val_accuracy: 0.7922 - val_loss: 0.4698
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7818 - loss: 0.4487 - val_accuracy: 0.7922 - val_loss: 0.4673
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7801 - loss: 0.4473 - val_accuracy: 0.7922 - val_loss: 0.4680
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7834 - loss: 0.4464 - val_accuracy: 0.7987 - val_loss: 0.4681
Epoch 15/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7818 - loss: 0.4444 - val_accuracy: 0.7922 - val_loss: 0.4667
Epoch 16/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7818 - loss: 0.4444 - val_accuracy: 0.7922 - val_loss: 0.4673
Epoch 17/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7866 - loss: 0.4417 - val_accuracy: 0.7857 - val_loss: 0.4692
Epoch 18/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7883 - loss: 0.4417 - val_accuracy: 0.7857 - val_loss: 0.4689
Epoch 19/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7866 - loss: 0.4397 - val_accuracy: 0.7792 - val_loss: 0.4686
Epoch 20/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7818 - loss: 0.4396 - val_accuracy: 0.7857 - val_loss: 0.4656
Epoch 21/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7866 - loss: 0.4379 - val_accuracy: 0.7922 - val_loss: 0.4659
Epoch 22/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7866 - loss: 0.4368 - val_accuracy: 0.7857 - val_loss: 0.4660
Epoch 23/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7850 - loss: 0.4356 - val_accuracy: 0.7987 - val_loss: 0.4645
Epoch 24/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7899 - loss: 0.4360 - val_accuracy: 0.7857 - val_loss: 0.4668
Epoch 25/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4339 - val_accuracy: 0.7857 - val_loss: 0.4659
Epoch 26/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7883 - loss: 0.4333 - val_accuracy: 0.7922 - val_loss: 0.4639
Epoch 27/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7866 - loss: 0.4328 - val_accuracy: 0.7922 - val_loss: 0.4612
Epoch 28/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7866 - loss: 0.4313 - val_accuracy: 0.7857 - val_loss: 0.4630
Epoch 29/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7915 - loss: 0.4304 - val_accuracy: 0.7857 - val_loss: 0.4641
Epoch 30/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7818 - loss: 0.4308 - val_accuracy: 0.7857 - val_loss: 0.4648
Epoch 31/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7915 - loss: 0.4306 - val_accuracy: 0.7922 - val_loss: 0.4620
Epoch 32/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7866 - loss: 0.4283 - val_accuracy: 0.7922 - val_loss: 0.4663
Epoch 33/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7834 - loss: 0.4269 - val_accuracy: 0.7922 - val_loss: 0.4674
Epoch 34/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7818 - loss: 0.4267 - val_accuracy: 0.7922 - val_loss: 0.4662
Epoch 35/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7899 - loss: 0.4260 - val_accuracy: 0.7857 - val_loss: 0.4662
Epoch 36/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7948 - loss: 0.4249 - val_accuracy: 0.7922 - val_loss: 0.4621
Epoch 37/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7915 - loss: 0.4257 - val_accuracy: 0.7922 - val_loss: 0.4645
Epoch 38/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7915 - loss: 0.4248 - val_accuracy: 0.7922 - val_loss: 0.4618
Epoch 39/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7948 - loss: 0.4231 - val_accuracy: 0.7922 - val_loss: 0.4631
Epoch 40/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7980 - loss: 0.4222 - val_accuracy: 0.7922 - val_loss: 0.4641
Epoch 41/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7964 - loss: 0.4210 - val_accuracy: 0.7857 - val_loss: 0.4653
Epoch 42/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7997 - loss: 0.4208 - val_accuracy: 0.7922 - val_loss: 0.4640
Epoch 43/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8029 - loss: 0.4198 - val_accuracy: 0.7857 - val_loss: 0.4624
Epoch 44/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7997 - loss: 0.4200 - val_accuracy: 0.7857 - val_loss: 0.4631
Epoch 45/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7997 - loss: 0.4184 - val_accuracy: 0.7922 - val_loss: 0.4629
Epoch 46/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8013 - loss: 0.4188 - val_accuracy: 0.7857 - val_loss: 0.4619
Epoch 47/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8046 - loss: 0.4174 - val_accuracy: 0.7922 - val_loss: 0.4611
Epoch 48/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8046 - loss: 0.4169 - val_accuracy: 0.7987 - val_loss: 0.4613
Epoch 49/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8029 - loss: 0.4162 - val_accuracy: 0.7922 - val_loss: 0.4623
Epoch 50/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7997 - loss: 0.4149 - val_accuracy: 0.7857 - val_loss: 0.4606
Epoch 51/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8029 - loss: 0.4147 - val_accuracy: 0.7922 - val_loss: 0.4610
Epoch 52/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7997 - loss: 0.4152 - val_accuracy: 0.7857 - val_loss: 0.4639
Epoch 53/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8029 - loss: 0.4131 - val_accuracy: 0.7922 - val_loss: 0.4612
Epoch 54/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8046 - loss: 0.4149 - val_accuracy: 0.7987 - val_loss: 0.4585
Epoch 55/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8046 - loss: 0.4130 - val_accuracy: 0.7857 - val_loss: 0.4609
Epoch 56/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8046 - loss: 0.4124 - val_accuracy: 0.7922 - val_loss: 0.4616
Epoch 57/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8094 - loss: 0.4124 - val_accuracy: 0.7857 - val_loss: 0.4651
Epoch 58/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8111 - loss: 0.4105 - val_accuracy: 0.7857 - val_loss: 0.4614
Epoch 59/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8046 - loss: 0.4098 - val_accuracy: 0.7857 - val_loss: 0.4627
Epoch 60/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8062 - loss: 0.4095 - val_accuracy: 0.7857 - val_loss: 0.4602
Epoch 61/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8094 - loss: 0.4090 - val_accuracy: 0.7922 - val_loss: 0.4594
Epoch 62/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8094 - loss: 0.4082 - val_accuracy: 0.7792 - val_loss: 0.4590
Epoch 63/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8094 - loss: 0.4077 - val_accuracy: 0.7857 - val_loss: 0.4601
Epoch 64/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8078 - loss: 0.4068 - val_accuracy: 0.7922 - val_loss: 0.4619
Epoch 65/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8094 - loss: 0.4060 - val_accuracy: 0.7922 - val_loss: 0.4602
Epoch 66/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8078 - loss: 0.4059 - val_accuracy: 0.7922 - val_loss: 0.4591
Epoch 67/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8143 - loss: 0.4050 - val_accuracy: 0.7922 - val_loss: 0.4597
Epoch 68/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8160 - loss: 0.4041 - val_accuracy: 0.7857 - val_loss: 0.4626
Epoch 69/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8094 - loss: 0.4039 - val_accuracy: 0.7857 - val_loss: 0.4634
Epoch 70/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8192 - loss: 0.4047 - val_accuracy: 0.7922 - val_loss: 0.4622
Epoch 71/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8225 - loss: 0.4046 - val_accuracy: 0.7857 - val_loss: 0.4645
Epoch 72/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8143 - loss: 0.4025 - val_accuracy: 0.7922 - val_loss: 0.4648
Epoch 73/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8176 - loss: 0.4010 - val_accuracy: 0.7987 - val_loss: 0.4632
Epoch 74/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8176 - loss: 0.4012 - val_accuracy: 0.7922 - val_loss: 0.4609
Epoch 75/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8176 - loss: 0.4013 - val_accuracy: 0.7857 - val_loss: 0.4620
Epoch 76/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8143 - loss: 0.4004 - val_accuracy: 0.7987 - val_loss: 0.4608
Epoch 77/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8208 - loss: 0.3994 - val_accuracy: 0.7922 - val_loss: 0.4615
Epoch 78/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8192 - loss: 0.3982 - val_accuracy: 0.7987 - val_loss: 0.4633
Epoch 79/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8208 - loss: 0.3983 - val_accuracy: 0.7922 - val_loss: 0.4644
Epoch 80/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8290 - loss: 0.3991 - val_accuracy: 0.7987 - val_loss: 0.4624
Epoch 81/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8241 - loss: 0.3971 - val_accuracy: 0.7987 - val_loss: 0.4610
Epoch 82/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8160 - loss: 0.3968 - val_accuracy: 0.8052 - val_loss: 0.4580
Epoch 83/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8208 - loss: 0.3957 - val_accuracy: 0.8052 - val_loss: 0.4614
Epoch 84/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8192 - loss: 0.3969 - val_accuracy: 0.8052 - val_loss: 0.4637
Epoch 85/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8225 - loss: 0.3966 - val_accuracy: 0.7922 - val_loss: 0.4625
Epoch 86/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8208 - loss: 0.3951 - val_accuracy: 0.7922 - val_loss: 0.4617
Epoch 87/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8192 - loss: 0.3948 - val_accuracy: 0.8052 - val_loss: 0.4608
Epoch 88/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8143 - loss: 0.3947 - val_accuracy: 0.7987 - val_loss: 0.4579
Epoch 89/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8274 - loss: 0.3943 - val_accuracy: 0.8052 - val_loss: 0.4592
Epoch 90/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8192 - loss: 0.3938 - val_accuracy: 0.8052 - val_loss: 0.4609
Epoch 91/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8241 - loss: 0.3928 - val_accuracy: 0.7987 - val_loss: 0.4622
Epoch 92/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8274 - loss: 0.3913 - val_accuracy: 0.8052 - val_loss: 0.4627
Epoch 93/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8160 - loss: 0.3915 - val_accuracy: 0.7987 - val_loss: 0.4606
Epoch 94/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8225 - loss: 0.3889 - val_accuracy: 0.8052 - val_loss: 0.4604
Epoch 95/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8306 - loss: 0.3894 - val_accuracy: 0.7987 - val_loss: 0.4628
Epoch 96/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8274 - loss: 0.3897 - val_accuracy: 0.8052 - val_loss: 0.4610
Epoch 97/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8306 - loss: 0.3892 - val_accuracy: 0.7987 - val_loss: 0.4638
Epoch 98/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8176 - loss: 0.3879 - val_accuracy: 0.7987 - val_loss: 0.4648
Epoch 99/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8208 - loss: 0.3889 - val_accuracy: 0.7922 - val_loss: 0.4670
Epoch 100/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8241 - loss: 0.3881 - val_accuracy: 0.8052 - val_loss: 0.4622

In [32]:
def build_model(hp):

  model = keras.Sequential()

  model.add(Dense(72, activation='relu', input_dim=8))

  for i in range(hp.Int('num_layers', 1, 10)):
    model.add(Dense(72, activation='relu'))

  model.add(Dense(1, activation='sigmoid'))


  model.compile(optimizer='rmsprop', loss='binary_crossentropy', metrics=['accuracy'])
  return model

In [33]:
tuner = kt.RandomSearch(
    build_model,
    objective='val_accuracy',
    max_trials=5,
    directory='nafis',
    project_name = 'num_layers')

In [34]:
tuner.search(X_train, y_train, epochs=5, validation_data=(X_test, y_test))

Trial 5 Complete [00h 00m 04s]
val_accuracy: 0.7922077775001526

Best val_accuracy So Far: 0.8116883039474487
Total elapsed time: 00h 00m 18s

In [35]:
tuner.get_best_hyperparameters()[0].values

{'num_layers': 2}

In [36]:
model = tuner.get_best_models(num_models=1)[0]

/usr/local/lib/python3.13/dist-packages/keras/src/saving/saving_lib.py:797: UserWarning: Skipping variable loading for optimizer 'rmsprop', because it has 2 variables whereas the saved optimizer has 10 variables.
  saveable.load_own_variables(weights_store.get(inner_path))

In [37]:
model.fit(X_train, y_train, epochs=100, initial_epoch=6, validation_data=(X_test, y_test))

Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - accuracy: 0.7752 - loss: 0.4438 - val_accuracy: 0.7857 - val_loss: 0.4780
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7801 - loss: 0.4338 - val_accuracy: 0.7987 - val_loss: 0.4761
Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7948 - loss: 0.4251 - val_accuracy: 0.7857 - val_loss: 0.4875
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7801 - loss: 0.4250 - val_accuracy: 0.8312 - val_loss: 0.4663
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7801 - loss: 0.4158 - val_accuracy: 0.8117 - val_loss: 0.4613
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8062 - loss: 0.4149 - val_accuracy: 0.8182 - val_loss: 0.4643
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7866 - loss: 0.4065 - val_accuracy: 0.7987 - val_loss: 0.4723
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7980 - loss: 0.4036 - val_accuracy: 0.8117 - val_loss: 0.4677
Epoch 15/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7997 - loss: 0.4007 - val_accuracy: 0.8052 - val_loss: 0.4746
Epoch 16/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8192 - loss: 0.3948 - val_accuracy: 0.8247 - val_loss: 0.4674
Epoch 17/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8225 - loss: 0.3899 - val_accuracy: 0.8182 - val_loss: 0.4674
Epoch 18/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8111 - loss: 0.3890 - val_accuracy: 0.8052 - val_loss: 0.4749
Epoch 19/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8306 - loss: 0.3824 - val_accuracy: 0.8117 - val_loss: 0.4684
Epoch 20/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8225 - loss: 0.3771 - val_accuracy: 0.8052 - val_loss: 0.4708
Epoch 21/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8290 - loss: 0.3735 - val_accuracy: 0.7922 - val_loss: 0.4925
Epoch 22/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8404 - loss: 0.3679 - val_accuracy: 0.7987 - val_loss: 0.4678
Epoch 23/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8339 - loss: 0.3697 - val_accuracy: 0.8117 - val_loss: 0.4836
Epoch 24/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8436 - loss: 0.3583 - val_accuracy: 0.8052 - val_loss: 0.4721
Epoch 25/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8306 - loss: 0.3594 - val_accuracy: 0.8117 - val_loss: 0.4688
Epoch 26/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8404 - loss: 0.3539 - val_accuracy: 0.8182 - val_loss: 0.4762
Epoch 27/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8583 - loss: 0.3468 - val_accuracy: 0.8117 - val_loss: 0.4743
Epoch 28/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8485 - loss: 0.3449 - val_accuracy: 0.7922 - val_loss: 0.4831
Epoch 29/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8469 - loss: 0.3398 - val_accuracy: 0.8182 - val_loss: 0.4777
Epoch 30/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8420 - loss: 0.3415 - val_accuracy: 0.8052 - val_loss: 0.4972
Epoch 31/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8550 - loss: 0.3353 - val_accuracy: 0.7857 - val_loss: 0.5070
Epoch 32/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8583 - loss: 0.3271 - val_accuracy: 0.8052 - val_loss: 0.4935
Epoch 33/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8664 - loss: 0.3253 - val_accuracy: 0.7727 - val_loss: 0.5136
Epoch 34/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - accuracy: 0.8616 - loss: 0.3185 - val_accuracy: 0.8052 - val_loss: 0.4993
Epoch 35/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8648 - loss: 0.3143 - val_accuracy: 0.7727 - val_loss: 0.5096
Epoch 36/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8697 - loss: 0.3080 - val_accuracy: 0.7922 - val_loss: 0.5166
Epoch 37/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - accuracy: 0.8681 - loss: 0.3052 - val_accuracy: 0.7987 - val_loss: 0.5301
Epoch 38/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8811 - loss: 0.3002 - val_accuracy: 0.8117 - val_loss: 0.5090
Epoch 39/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8844 - loss: 0.2944 - val_accuracy: 0.7792 - val_loss: 0.5328
Epoch 40/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - accuracy: 0.8811 - loss: 0.2944 - val_accuracy: 0.7792 - val_loss: 0.5521
Epoch 41/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8893 - loss: 0.2818 - val_accuracy: 0.7727 - val_loss: 0.5380
Epoch 42/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8893 - loss: 0.2870 - val_accuracy: 0.7922 - val_loss: 0.5201
Epoch 43/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8974 - loss: 0.2695 - val_accuracy: 0.8117 - val_loss: 0.5677
Epoch 44/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8958 - loss: 0.2704 - val_accuracy: 0.7597 - val_loss: 0.6371
Epoch 45/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8941 - loss: 0.2656 - val_accuracy: 0.7727 - val_loss: 0.5632
Epoch 46/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8925 - loss: 0.2638 - val_accuracy: 0.7727 - val_loss: 0.6046
Epoch 47/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8941 - loss: 0.2586 - val_accuracy: 0.7792 - val_loss: 0.5745
Epoch 48/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9039 - loss: 0.2500 - val_accuracy: 0.7792 - val_loss: 0.5740
Epoch 49/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8990 - loss: 0.2493 - val_accuracy: 0.7922 - val_loss: 0.5715
Epoch 50/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9007 - loss: 0.2447 - val_accuracy: 0.7662 - val_loss: 0.5513
Epoch 51/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9072 - loss: 0.2381 - val_accuracy: 0.7922 - val_loss: 0.6209
Epoch 52/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9055 - loss: 0.2351 - val_accuracy: 0.7597 - val_loss: 0.5614
Epoch 53/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9137 - loss: 0.2270 - val_accuracy: 0.7792 - val_loss: 0.5647
Epoch 54/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9007 - loss: 0.2210 - val_accuracy: 0.8052 - val_loss: 0.5952
Epoch 55/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9218 - loss: 0.2198 - val_accuracy: 0.7727 - val_loss: 0.6056
Epoch 56/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9169 - loss: 0.2246 - val_accuracy: 0.7987 - val_loss: 0.6236
Epoch 57/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9251 - loss: 0.2094 - val_accuracy: 0.7922 - val_loss: 0.6280
Epoch 58/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9283 - loss: 0.2026 - val_accuracy: 0.7857 - val_loss: 0.6574
Epoch 59/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9121 - loss: 0.2053 - val_accuracy: 0.7857 - val_loss: 0.6188
Epoch 60/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9218 - loss: 0.1942 - val_accuracy: 0.7792 - val_loss: 0.6340
Epoch 61/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9316 - loss: 0.1908 - val_accuracy: 0.7792 - val_loss: 0.6024
Epoch 62/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9283 - loss: 0.1856 - val_accuracy: 0.7987 - val_loss: 0.6502
Epoch 63/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9267 - loss: 0.1767 - val_accuracy: 0.7727 - val_loss: 0.6841
Epoch 64/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9349 - loss: 0.1834 - val_accuracy: 0.7727 - val_loss: 0.7428
Epoch 65/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9349 - loss: 0.1732 - val_accuracy: 0.7922 - val_loss: 0.7041
Epoch 66/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9446 - loss: 0.1717 - val_accuracy: 0.7532 - val_loss: 0.6618
Epoch 67/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9430 - loss: 0.1594 - val_accuracy: 0.7987 - val_loss: 0.6841
Epoch 68/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9300 - loss: 0.1651 - val_accuracy: 0.7143 - val_loss: 0.7175
Epoch 69/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9479 - loss: 0.1599 - val_accuracy: 0.7792 - val_loss: 0.7083
Epoch 70/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9446 - loss: 0.1530 - val_accuracy: 0.7403 - val_loss: 0.7115
Epoch 71/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9495 - loss: 0.1490 - val_accuracy: 0.7662 - val_loss: 0.7571
Epoch 72/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9446 - loss: 0.1424 - val_accuracy: 0.7987 - val_loss: 0.7288
Epoch 73/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9577 - loss: 0.1407 - val_accuracy: 0.7987 - val_loss: 0.7725
Epoch 74/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9479 - loss: 0.1360 - val_accuracy: 0.7727 - val_loss: 0.7788
Epoch 75/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9577 - loss: 0.1276 - val_accuracy: 0.7468 - val_loss: 0.7785
Epoch 76/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9642 - loss: 0.1247 - val_accuracy: 0.7792 - val_loss: 0.8012
Epoch 77/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9609 - loss: 0.1279 - val_accuracy: 0.7597 - val_loss: 0.8297
Epoch 78/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9674 - loss: 0.1167 - val_accuracy: 0.7597 - val_loss: 0.7858
Epoch 79/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9560 - loss: 0.1241 - val_accuracy: 0.7662 - val_loss: 0.7939
Epoch 80/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9642 - loss: 0.1128 - val_accuracy: 0.7338 - val_loss: 0.8019
Epoch 81/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9658 - loss: 0.1097 - val_accuracy: 0.7468 - val_loss: 0.8939
Epoch 82/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9707 - loss: 0.1052 - val_accuracy: 0.7597 - val_loss: 0.8392
Epoch 83/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9723 - loss: 0.1049 - val_accuracy: 0.7532 - val_loss: 0.9192
Epoch 84/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9674 - loss: 0.1014 - val_accuracy: 0.7727 - val_loss: 0.8829
Epoch 85/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9739 - loss: 0.0985 - val_accuracy: 0.7468 - val_loss: 0.8554
Epoch 86/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9756 - loss: 0.0961 - val_accuracy: 0.7403 - val_loss: 0.8984
Epoch 87/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9723 - loss: 0.0904 - val_accuracy: 0.7662 - val_loss: 1.0258
Epoch 88/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9691 - loss: 0.0946 - val_accuracy: 0.7338 - val_loss: 0.9371
Epoch 89/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9739 - loss: 0.0832 - val_accuracy: 0.7208 - val_loss: 1.0728
Epoch 90/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9691 - loss: 0.0885 - val_accuracy: 0.7403 - val_loss: 0.9099
Epoch 91/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9805 - loss: 0.0852 - val_accuracy: 0.7597 - val_loss: 1.0460
Epoch 92/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9772 - loss: 0.0797 - val_accuracy: 0.7403 - val_loss: 0.9885
Epoch 93/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9788 - loss: 0.0720 - val_accuracy: 0.7338 - val_loss: 1.0935
Epoch 94/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9723 - loss: 0.0777 - val_accuracy: 0.7468 - val_loss: 0.9997
Epoch 95/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9805 - loss: 0.0705 - val_accuracy: 0.7403 - val_loss: 1.0785
Epoch 96/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9788 - loss: 0.0764 - val_accuracy: 0.7532 - val_loss: 1.0610
Epoch 97/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9788 - loss: 0.0692 - val_accuracy: 0.7338 - val_loss: 1.1323
Epoch 98/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9837 - loss: 0.0565 - val_accuracy: 0.7403 - val_loss: 1.0216
Epoch 99/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9870 - loss: 0.0668 - val_accuracy: 0.7792 - val_loss: 1.0872
Epoch 100/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9788 - loss: 0.0649 - val_accuracy: 0.7532 - val_loss: 1.1740

In [106]:
def build_model(hp):
  model = keras.Sequential()

  num_layers = hp.Int('num_layers', min_value=1, max_value=10)


  for i in range(num_layers):

    if i == 0:
      model.add(
          keras.layers.Dense(
            hp.Int('units' + str(i), min_value=8, max_value=128, step=8),
            activation=hp.Choice('activation' + str(i), values=['relu', 'tanh', 'sigmoid']),
            input_dim=8
            )
      )
      model.add(
          Dropout(hp.Choice('dropout' + str(i), values=[0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]))
      )

    else:
      model.add(
          keras.layers.Dense(
            hp.Int('units' + str(i), min_value=8, max_value=128, step=8),
            activation=hp.Choice('activation' + str(i), values=['relu', 'tanh', 'sigmoid'])
            )
      )
      model.add(
        Dropout(hp.Choice('dropout' + str(i), values=[0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]))
      )

  model.add(keras.layers.Dense(1, activation='sigmoid'))

  model.compile(
      optimizer=hp.Choice('optimizer', values=['rmsprop', 'adam', 'sgd', 'adadelta']),
      loss='binary_crossentropy',
      metrics=['accuracy']
      )

  return model

In [107]:
tuner = kt.RandomSearch(
    build_model,
    objective = 'val_accuracy',
    max_trials=20,
    directory = 'mydir',
    project_name = 'final tune 1'
)

/usr/local/lib/python3.13/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [108]:
tuner.search(X_train, y_train, epochs=5, validation_data=(X_test, y_test))

Trial 20 Complete [00h 00m 05s]
val_accuracy: 0.798701286315918

Best val_accuracy So Far: 0.8181818127632141
Total elapsed time: 00h 01m 41s

In [109]:
tuner.get_best_hyperparameters()[0].values

{'num_layers': 3,
 'units0': 128,
 'activation0': 'tanh',
 'dropout0': 0.6,
 'optimizer': 'adam',
 'units1': 72,
 'activation1': 'tanh',
 'dropout1': 0.4,
 'units2': 64,
 'activation2': 'tanh',
 'dropout2': 0.4,
 'units3': 32,
 'activation3': 'relu',
 'dropout3': 0.1,
 'units4': 56,
 'activation4': 'sigmoid',
 'dropout4': 0.2,
 'units5': 104,
 'activation5': 'sigmoid',
 'dropout5': 0.5,
 'units6': 104,
 'activation6': 'relu',
 'dropout6': 0.3,
 'units7': 24,
 'activation7': 'tanh',
 'dropout7': 0.5,
 'units8': 72,
 'activation8': 'tanh',
 'dropout8': 0.9,
 'units9': 64,
 'activation9': 'relu',
 'dropout9': 0.6}

In [111]:
model = tuner.get_best_models(num_models=1)[0]

/usr/local/lib/python3.13/dist-packages/keras/src/saving/saving_lib.py:797: UserWarning: Skipping variable loading for optimizer 'adam', because it has 2 variables whereas the saved optimizer has 18 variables.
  saveable.load_own_variables(weights_store.get(inner_path))

In [112]:
model.fit(X_train, y_train, epochs=100, initial_epoch=6, validation_data=(X_test, y_test))

Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - accuracy: 0.7622 - loss: 0.4997 - val_accuracy: 0.8052 - val_loss: 0.4592
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7329 - loss: 0.5397 - val_accuracy: 0.7922 - val_loss: 0.4578
Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7459 - loss: 0.5162 - val_accuracy: 0.7727 - val_loss: 0.4601
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7524 - loss: 0.5114 - val_accuracy: 0.7922 - val_loss: 0.4601
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7590 - loss: 0.5147 - val_accuracy: 0.7727 - val_loss: 0.4595
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7394 - loss: 0.5047 - val_accuracy: 0.7727 - val_loss: 0.4596
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7492 - loss: 0.5101 - val_accuracy: 0.7857 - val_loss: 0.4616
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7752 - loss: 0.4942 - val_accuracy: 0.7792 - val_loss: 0.4635
Epoch 15/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7378 - loss: 0.5170 - val_accuracy: 0.7727 - val_loss: 0.4642
Epoch 16/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7410 - loss: 0.5089 - val_accuracy: 0.7662 - val_loss: 0.4611
Epoch 17/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7524 - loss: 0.5012 - val_accuracy: 0.7727 - val_loss: 0.4597
Epoch 18/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7671 - loss: 0.4890 - val_accuracy: 0.7727 - val_loss: 0.4643
Epoch 19/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7492 - loss: 0.5046 - val_accuracy: 0.7792 - val_loss: 0.4574
Epoch 20/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7606 - loss: 0.4883 - val_accuracy: 0.7857 - val_loss: 0.4624
Epoch 21/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7557 - loss: 0.5103 - val_accuracy: 0.7727 - val_loss: 0.4638
Epoch 22/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7655 - loss: 0.4975 - val_accuracy: 0.7922 - val_loss: 0.4653
Epoch 23/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7687 - loss: 0.4899 - val_accuracy: 0.7922 - val_loss: 0.4618
Epoch 24/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7443 - loss: 0.5184 - val_accuracy: 0.7792 - val_loss: 0.4668
Epoch 25/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7492 - loss: 0.4978 - val_accuracy: 0.7857 - val_loss: 0.4645
Epoch 26/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7704 - loss: 0.4853 - val_accuracy: 0.7857 - val_loss: 0.4678
Epoch 27/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7671 - loss: 0.4917 - val_accuracy: 0.7857 - val_loss: 0.4615
Epoch 28/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7524 - loss: 0.5128 - val_accuracy: 0.7792 - val_loss: 0.4641
Epoch 29/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7655 - loss: 0.5014 - val_accuracy: 0.7922 - val_loss: 0.4602
Epoch 30/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7590 - loss: 0.4930 - val_accuracy: 0.7792 - val_loss: 0.4626
Epoch 31/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7590 - loss: 0.4899 - val_accuracy: 0.7857 - val_loss: 0.4627
Epoch 32/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7590 - loss: 0.4897 - val_accuracy: 0.7792 - val_loss: 0.4628
Epoch 33/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7606 - loss: 0.5022 - val_accuracy: 0.7922 - val_loss: 0.4584
Epoch 34/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7671 - loss: 0.4946 - val_accuracy: 0.7857 - val_loss: 0.4623
Epoch 35/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7557 - loss: 0.4882 - val_accuracy: 0.8052 - val_loss: 0.4563
Epoch 36/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7736 - loss: 0.4808 - val_accuracy: 0.7922 - val_loss: 0.4559
Epoch 37/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7655 - loss: 0.4746 - val_accuracy: 0.8052 - val_loss: 0.4589
Epoch 38/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7606 - loss: 0.4879 - val_accuracy: 0.7922 - val_loss: 0.4571
Epoch 39/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7687 - loss: 0.4748 - val_accuracy: 0.7857 - val_loss: 0.4594
Epoch 40/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7508 - loss: 0.4992 - val_accuracy: 0.7857 - val_loss: 0.4644
Epoch 41/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7622 - loss: 0.4914 - val_accuracy: 0.7857 - val_loss: 0.4628
Epoch 42/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7573 - loss: 0.4935 - val_accuracy: 0.7792 - val_loss: 0.4643
Epoch 43/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7459 - loss: 0.4878 - val_accuracy: 0.7792 - val_loss: 0.4670
Epoch 44/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7524 - loss: 0.4904 - val_accuracy: 0.7792 - val_loss: 0.4653
Epoch 45/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7704 - loss: 0.4747 - val_accuracy: 0.7922 - val_loss: 0.4655
Epoch 46/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7524 - loss: 0.4907 - val_accuracy: 0.7922 - val_loss: 0.4609
Epoch 47/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7573 - loss: 0.5012 - val_accuracy: 0.7857 - val_loss: 0.4612
Epoch 48/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7671 - loss: 0.4946 - val_accuracy: 0.8052 - val_loss: 0.4572
Epoch 49/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7590 - loss: 0.4879 - val_accuracy: 0.7922 - val_loss: 0.4624
Epoch 50/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7459 - loss: 0.4956 - val_accuracy: 0.7857 - val_loss: 0.4675
Epoch 51/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7883 - loss: 0.4864 - val_accuracy: 0.7792 - val_loss: 0.4644
Epoch 52/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7590 - loss: 0.4808 - val_accuracy: 0.8052 - val_loss: 0.4597
Epoch 53/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7622 - loss: 0.4813 - val_accuracy: 0.7922 - val_loss: 0.4590
Epoch 54/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7736 - loss: 0.4686 - val_accuracy: 0.7922 - val_loss: 0.4571
Epoch 55/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7638 - loss: 0.4777 - val_accuracy: 0.7727 - val_loss: 0.4605
Epoch 56/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7720 - loss: 0.4874 - val_accuracy: 0.7727 - val_loss: 0.4611
Epoch 57/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7638 - loss: 0.4893 - val_accuracy: 0.7792 - val_loss: 0.4581
Epoch 58/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7606 - loss: 0.4794 - val_accuracy: 0.7727 - val_loss: 0.4594
Epoch 59/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7736 - loss: 0.4754 - val_accuracy: 0.7792 - val_loss: 0.4584
Epoch 60/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7638 - loss: 0.4778 - val_accuracy: 0.7857 - val_loss: 0.4563
Epoch 61/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7883 - loss: 0.4720 - val_accuracy: 0.7922 - val_loss: 0.4555
Epoch 62/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7736 - loss: 0.4780 - val_accuracy: 0.7922 - val_loss: 0.4577
Epoch 63/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7557 - loss: 0.4900 - val_accuracy: 0.7922 - val_loss: 0.4572
Epoch 64/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7557 - loss: 0.4752 - val_accuracy: 0.7922 - val_loss: 0.4579
Epoch 65/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7720 - loss: 0.4655 - val_accuracy: 0.7922 - val_loss: 0.4555
Epoch 66/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7557 - loss: 0.4868 - val_accuracy: 0.7987 - val_loss: 0.4581
Epoch 67/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7606 - loss: 0.4711 - val_accuracy: 0.7792 - val_loss: 0.4610
Epoch 68/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7638 - loss: 0.4794 - val_accuracy: 0.7857 - val_loss: 0.4631
Epoch 69/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7443 - loss: 0.4855 - val_accuracy: 0.7857 - val_loss: 0.4566
Epoch 70/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7736 - loss: 0.4660 - val_accuracy: 0.7922 - val_loss: 0.4563
Epoch 71/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7671 - loss: 0.4852 - val_accuracy: 0.7922 - val_loss: 0.4535
Epoch 72/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7769 - loss: 0.4652 - val_accuracy: 0.7922 - val_loss: 0.4544
Epoch 73/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7866 - loss: 0.4705 - val_accuracy: 0.7922 - val_loss: 0.4557
Epoch 74/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7671 - loss: 0.4741 - val_accuracy: 0.7857 - val_loss: 0.4534
Epoch 75/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7736 - loss: 0.4653 - val_accuracy: 0.7857 - val_loss: 0.4550
Epoch 76/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7752 - loss: 0.4745 - val_accuracy: 0.7857 - val_loss: 0.4536
Epoch 77/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7606 - loss: 0.4802 - val_accuracy: 0.7857 - val_loss: 0.4567
Epoch 78/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7573 - loss: 0.4776 - val_accuracy: 0.7857 - val_loss: 0.4517
Epoch 79/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7720 - loss: 0.4643 - val_accuracy: 0.7987 - val_loss: 0.4514
Epoch 80/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7687 - loss: 0.4645 - val_accuracy: 0.7922 - val_loss: 0.4529
Epoch 81/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7866 - loss: 0.4614 - val_accuracy: 0.7922 - val_loss: 0.4525
Epoch 82/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7818 - loss: 0.4646 - val_accuracy: 0.7922 - val_loss: 0.4518
Epoch 83/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7720 - loss: 0.4641 - val_accuracy: 0.7922 - val_loss: 0.4548
Epoch 84/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7704 - loss: 0.4688 - val_accuracy: 0.7922 - val_loss: 0.4566
Epoch 85/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7671 - loss: 0.4857 - val_accuracy: 0.7987 - val_loss: 0.4505
Epoch 86/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7736 - loss: 0.4694 - val_accuracy: 0.7987 - val_loss: 0.4522
Epoch 87/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7622 - loss: 0.4660 - val_accuracy: 0.7922 - val_loss: 0.4533
Epoch 88/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7622 - loss: 0.4758 - val_accuracy: 0.7922 - val_loss: 0.4540
Epoch 89/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7785 - loss: 0.4700 - val_accuracy: 0.7987 - val_loss: 0.4503
Epoch 90/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7769 - loss: 0.4560 - val_accuracy: 0.8117 - val_loss: 0.4496
Epoch 91/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7769 - loss: 0.4638 - val_accuracy: 0.7987 - val_loss: 0.4561
Epoch 92/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7785 - loss: 0.4667 - val_accuracy: 0.7987 - val_loss: 0.4570
Epoch 93/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7622 - loss: 0.4741 - val_accuracy: 0.7987 - val_loss: 0.4524
Epoch 94/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7752 - loss: 0.4572 - val_accuracy: 0.7987 - val_loss: 0.4555
Epoch 95/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7655 - loss: 0.4710 - val_accuracy: 0.7922 - val_loss: 0.4543
Epoch 96/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7785 - loss: 0.4584 - val_accuracy: 0.7987 - val_loss: 0.4539
Epoch 97/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7834 - loss: 0.4558 - val_accuracy: 0.7987 - val_loss: 0.4546
Epoch 98/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7736 - loss: 0.4512 - val_accuracy: 0.7987 - val_loss: 0.4602
Epoch 99/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7655 - loss: 0.4832 - val_accuracy: 0.7987 - val_loss: 0.4584
Epoch 100/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7638 - loss: 0.4629 - val_accuracy: 0.7987 - val_loss: 0.4599